#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
#
Name     : gnome-console
Version  : 44.4
Release  : 11
URL      : https://download.gnome.org/sources/gnome-console/44/gnome-console-44.4.tar.xz
Source0  : https://download.gnome.org/sources/gnome-console/44/gnome-console-44.4.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: gnome-console-bin = %{version}-%{release}
Requires: gnome-console-data = %{version}-%{release}
Requires: gnome-console-license = %{version}-%{release}
Requires: gnome-console-locales = %{version}-%{release}
BuildRequires : appstream-glib
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : pkgconfig(libadwaita-1)
BuildRequires : pkgconfig(libgtop-2.0)
BuildRequires : pkgconfig(vte-2.91-gtk4)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# Console
![](logo.png)
A minimal terminal for GNOME
Console is supposed to be a simple terminal emulator for the average user to carry out simple cli tasks and aims to be a ‘core’ app for GNOME/Phosh

%package bin
Summary: bin components for the gnome-console package.
Group: Binaries
Requires: gnome-console-data = %{version}-%{release}
Requires: gnome-console-license = %{version}-%{release}

%description bin
bin components for the gnome-console package.


%package data
Summary: data components for the gnome-console package.
Group: Data

%description data
data components for the gnome-console package.


%package license
Summary: license components for the gnome-console package.
Group: Default

%description license
license components for the gnome-console package.


%package locales
Summary: locales components for the gnome-console package.
Group: Default

%description locales
locales components for the gnome-console package.


%prep
%setup -q -n gnome-console-44.4
cd %{_builddir}/gnome-console-44.4
pushd ..
cp -a gnome-console-44.4 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1691601918
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -O3" CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs

%install
mkdir -p %{buildroot}/usr/share/package-licenses/gnome-console
cp %{_builddir}/gnome-console-%{version}/COPYING %{buildroot}/usr/share/package-licenses/gnome-console/338650eb7a42dd9bc1f1c6961420f2633b24932d || :
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang kgx
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/kgx
/usr/bin/kgx

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.gnome.Console.desktop
/usr/share/dbus-1/services/org.gnome.Console.service
/usr/share/glib-2.0/schemas/org.gnome.Console.gschema.xml
/usr/share/icons/hicolor/scalable/apps/org.gnome.Console.svg
/usr/share/icons/hicolor/symbolic/apps/org.gnome.Console-symbolic.svg
/usr/share/metainfo/org.gnome.Console.metainfo.xml

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gnome-console/338650eb7a42dd9bc1f1c6961420f2633b24932d

%files locales -f kgx.lang
%defattr(-,root,root,-)

